apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    #requirepass pzxy@123456
    pidfile /var/run/redis_6379.pid
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    appendonly yes
    appendfilename "appendonly.aof"
    dir /data
    logfile "/data/redis-6379.log"
