---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piwigo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piwigo
  template:
    metadata:
      labels:
        app: piwigo
    spec:
      containers:
      - name: piwigo
        image: lscr.io/linuxserver/piwigo:15.5.0
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC+8"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: gallery-volume
          mountPath: /gallery
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: piwigo-pvc-config
      - name: gallery-volume
        persistentVolumeClaim:
          claimName: piwigo-pvc-data
---
apiVersion: v1
kind: Service
metadata:
  name: piwigo-service
spec:
  type: NodePort
  selector:
    app: piwigo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32352