apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
#  selector:
#    matchLabels:
#      app: batch-job
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: jasonkay/batch-job:latest
