apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: redis
      volumeMounts:
        - name: mongo
          mountPath: "/etc/foo"
          readOnly: true
  volumes:
    - name: mongo
      secret:
        secretName: mongo-secret
